site_name: ktpack
site_url: https://drewcarlson.github.io/ktpack/
repo_url: https://github.com/drewcarlson/ktpack
edit_uri: edit/main/docs/
docs_dir: docs
site_description: The simplest tool for building and publishing Kotlin software.
remote_branch: gh-pages
copyright: 'Copyright &copy; 2023 Drew Carlson'

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mike
  - markdownextradata: { }

extra:
  project: Ktpack
  lib_version: !ENV [ VERSION, '0.0.1-test' ]
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/DrewCarlson
    - icon: fontawesome/brands/github
      link: https://github.com/DrewCarlson/ktpack

nav:
  - index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Development:
      - Environment Setup: development/environment-setup.md
      - CLI Architecture: development/cli-architecture.md
      - Documentation: development/documentation.md
  - Motivation: motivation.md
