package ktpack.compilation

import co.touchlab.kermit.Logger
import io.github.z4kn4fein.semver.Version
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlinx.coroutines.invoke
import ksubprocess.*
import ktfio.*
import ktpack.*
import ktpack.compilation.dependencies.MavenDependencyResolver
import ktpack.compilation.dependencies.models.DependencyNode
import ktpack.compilation.dependencies.models.dependencyTreeString
import ktpack.compilation.dependencies.models.resolveAndFlatten
import ktpack.configuration.*
import ktpack.manifest.DependencyToml
import ktpack.manifest.ManifestToml
import ktpack.util.*
import okio.Path
import okio.Path.Companion.toPath
import kotlin.random.Random

/**
 * This class uses a Ktpack [ModuleConf] generated by a pack.toml manifest
 * and a specific action selected by the CLI to produce kotlin compiler
 * arguments with the correct list of kotlin source files and libraries.
 *
 * @param module The root module configuration to build.
 * @param context The cli run context.
 * @param modulePath The root directory containing the pack.toml manifest.
 */
// https://github.com/JetBrains/kotlin/blob/master/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2NativeCompilerArguments.kt
// https://github.com/JetBrains/kotlin/blob/master/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2JSCompilerArguments.kt
// https://github.com/JetBrains/kotlin/blob/master/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2JVMCompilerArguments.kt
// https://github.com/JetBrains/kotlin/blob/master/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/CommonCompilerArguments.kt
// https://kotlinlang.org/docs/compiler-reference.html
class ModuleBuilder(
    private val manifest: ManifestToml,
    private val context: CliContext,
    val modulePath: Path,
) {

    enum class BuildType { BIN, LIB, TEST }

    private val logger = Logger.withTag(ModuleBuilder::class.simpleName.orEmpty())
    private val outFolder = modulePath / "out"
    private val srcFolder = modulePath / "src"

    private val module = manifest.module
    private val resolver = MavenDependencyResolver(manifest, context.http)
    internal val sourceCollector = KotlinSourceCollector(srcFolder)

    init {
        require(modulePath.isAbsolute) {
            "ModuleBuilder requires modulePath to be absolute: $modulePath"
        }
    }

    suspend fun buildCommonLib(
        platformSources: CollectedSource,
        releaseMode: Boolean,
        target: KotlinTarget,
        buildType: BuildType,
        libs: List<String>? = null,
    ): ArtifactResult = Dispatchers.IO {
        val dependencyScopes = listOf(DependencyScope.IMPLEMENTATION, DependencyScope.API)
        val dependencyTree = resolveRootDependencyTree(listOf(target), dependencyScopes, includeCommon = true)

        val collectedSourceFiles = sourceCollector.collect(null, buildType)
        if (collectedSourceFiles.isEmpty && platformSources.isEmpty) {
            return@IO ArtifactResult.NoSourceFiles
        }

        val resolvedLibs = libs ?: assembleDependencies(dependencyTree, false, target)
            .flatMap { it.artifacts }
        val modeString = if (releaseMode) "release" else "debug"
        val commonLibOutput = outFolder / target.name.lowercase() / modeString / "klib" / "common"
        commonLibOutput.parent?.let { parent ->
            if (!parent.exists()) parent.mkdirs()
        }
        val (result, duration) = measureSeconds {
            startKotlinCompiler(
                sourceFiles = platformSources.sourceFiles + listOfNotNull(platformSources.mainFile),
                commonSourceFiles = collectedSourceFiles.sourceFiles + listOfNotNull(collectedSourceFiles.mainFile),
                releaseMode = releaseMode,
                output = commonLibOutput,
                target = target,
                isBinary = false,
                libs = resolvedLibs,
                isTest = false,
                isMultiplatform = true,
            )
        }

        if (result.exitCode == 0) {
            ArtifactResult.Success(
                target = target,
                artifactPath = "${commonLibOutput}.klib",
                compilationDuration = duration,
                outputText = listOf(result.output, result.errors).joinToString("\n"),
                dependencyArtifacts = resolvedLibs,
            )
        } else {
            ArtifactResult.ProcessError(result.exitCode, result.output)
        }
    }

    suspend fun buildTest(
        target: KotlinTarget,
        libs: List<String>? = null,
    ): ArtifactResult = Dispatchers.IO {
        val dependencyTree = resolveRootDependencyTree(listOf(target), DependencyScope.entries)

        val collectedSourceFiles = sourceCollector.collect(target, BuildType.TEST)
        if (collectedSourceFiles.isEmpty) {
            return@IO ArtifactResult.NoSourceFiles
        }

        val resolvedLibs = libs ?: assembleDependencies(dependencyTree, false, target)
            .flatMap { it.artifacts }
        val (result, duration) = measureSeconds {
            startKotlinCompiler(
                sourceFiles = collectedSourceFiles.sourceFiles,
                releaseMode = false,
                output = outFolder / "test" / target.name.lowercase() / module.name,
                target = target,
                isBinary = true,
                libs = resolvedLibs,
                isTest = true,
            )
        }

        val outputPath = outFolder / "test" / target.name.lowercase() / "${module.name}${target.executableExt}"

        return@IO if (result.exitCode == 0) {
            ArtifactResult.Success(
                target = target,
                compilationDuration = duration,
                dependencyArtifacts = resolvedLibs,
                artifactPath = outputPath.toString(),
                outputText = listOf(result.output, result.errors).joinToString("\n"),
            )
        } else {
            ArtifactResult.ProcessError(result.exitCode, result.errors.ifBlank { result.output })
        }
    }

    suspend fun buildBin(
        releaseMode: Boolean,
        binName: String,
        target: KotlinTarget,
        libs: List<String>? = null,
    ): ArtifactResult = Dispatchers.IO {
        val collectedSourceFiles = sourceCollector.collect(target, BuildType.BIN)
        if (collectedSourceFiles.isEmpty) {
            // TODO: Restore this check, but consider common sources
            //return@IO ArtifactResult.NoSourceFiles
        }

        val commonLibPath = if (target == KotlinTarget.JVM) {
            null
        } else {
            when (val result = buildCommonLib(collectedSourceFiles, releaseMode, target, BuildType.BIN, libs)) {
                is ArtifactResult.Success -> result.artifactPath
                ArtifactResult.NoSourceFiles -> null
                ArtifactResult.NoArtifactFound,
                is ArtifactResult.ProcessError -> return@IO result
            }
        }

        val dependencyTree = resolveRootDependencyTree(listOf(target), includeCommon = true)

        val selectedBinFile = if (binName == module.name) {
            collectedSourceFiles.mainFile?.toPath()
        } else {
            collectedSourceFiles.binFiles.firstNotNullOfOrNull { filePath ->
                filePath.toPath().takeIf { it.nameWithoutExtension == binName }
            }
        } // TODO: ?: return@IO ArtifactResult.NoArtifactFound
        //    Restore, but consider common sources

        val modeString = if (releaseMode) "release" else "debug"
        val targetBinDir = outFolder / target.name.lowercase() / modeString / "bin"
        if (!targetBinDir.exists()) targetBinDir.mkdirs()
        val outputPath = targetBinDir / binName
        val resolvedLibs = libs ?: assembleDependencies(dependencyTree, releaseMode, target)
            .flatMap { it.artifacts }
        // TODO: Improve handling for JVM (one-shot) MPP compilation
        val commonSources by lazy(LazyThreadSafetyMode.NONE) {
            sourceCollector.collect(null, BuildType.BIN)
        }
        val (result, duration) = measureSeconds {
            startKotlinCompiler(
                sourceFiles = if (commonLibPath == null) {
                    val mergedSources = commonSources.merge(collectedSourceFiles)
                    mergedSources.sourceFiles + listOfNotNull(selectedBinFile?.toString())
                } else {
                    emptyList()
                },
                commonSourceFiles = if (commonLibPath == null) {
                    commonSources.sourceFiles + listOfNotNull(commonSources.mainFile)
                } else {
                    emptyList()
                },
                releaseMode = releaseMode,
                output = outputPath,
                target = target,
                isBinary = true,
                isTest = false,
                isMultiplatform = commonLibPath == null,
                includes = listOfNotNull(commonLibPath),
                libs = resolvedLibs,
            )
        }
        return@IO if (result.exitCode == 0) {
            ArtifactResult.Success(
                target = target,
                compilationDuration = duration,
                dependencyArtifacts = resolvedLibs,
                artifactPath = "${outputPath}${target.executableExt}",
                outputText = listOf(result.output, result.errors).joinToString("\n"),
            )
        } else {
            ArtifactResult.ProcessError(result.exitCode, result.errors.ifBlank { result.output })
        }
    }

    suspend fun buildLib(
        releaseMode: Boolean,
        target: KotlinTarget,
        libs: List<String>? = null,
    ): ArtifactResult = Dispatchers.Default {
        val collectedSourceFiles = sourceCollector.collect(target, BuildType.LIB)

        val commonLibPath =
            (buildCommonLib(collectedSourceFiles, releaseMode, target, BuildType.LIB, libs) as ArtifactResult.Success)
            .artifactPath

        val sourceFiles = collectedSourceFiles.sourceFiles
        if (collectedSourceFiles.isEmpty || !collectedSourceFiles.hasLibFile) {
            return@Default ArtifactResult.NoArtifactFound
        }
        val libFile = checkNotNull(collectedSourceFiles.mainFile).toPath()
        val dependencyTree = resolveRootDependencyTree(listOf(target))

        val modeString = if (releaseMode) "release" else "debug"
        val targetLibDir = outFolder / target.name.lowercase() / modeString / "lib"
        if (!targetLibDir.exists()) targetLibDir.mkdirs()

        val resolvedLibs = libs ?: assembleDependencies(dependencyTree, releaseMode, target)
            .flatMap { it.artifacts }
        val outputPath = targetLibDir / module.name
        val (result, duration) = measureSeconds {
            startKotlinCompiler(
                sourceFiles = sourceFiles + libFile.toString(),
                releaseMode = releaseMode,
                output = outputPath,
                target = target,
                isBinary = false,
                isTest = false,
                libs = listOfNotNull(commonLibPath) + resolvedLibs,
            )
        }
        return@Default if (result.exitCode == 0) {
            ArtifactResult.Success(
                target = target,
                artifactPath = "${outputPath}${target.libraryExt}",
                compilationDuration = duration,
                outputText = listOf(result.output, result.errors).joinToString("\n"),
                dependencyArtifacts = resolvedLibs,
            )
        } else {
            ArtifactResult.ProcessError(result.exitCode, result.errors.ifBlank { result.output })
        }
    }

    suspend fun buildAllBins(releaseMode: Boolean, target: KotlinTarget): List<ArtifactResult> {
        val dependencyTree = resolveRootDependencyTree(listOf(target))

        logger.d { dependencyTree.dependencyTreeString() }

        if (!outFolder.exists() && !outFolder.mkdirs().exists()) {
            error("Could not create build folder: $outFolder")
        }

        val resolvedDeps = assembleDependencies(dependencyTree, releaseMode, target)
            .flatMap { it.artifacts }
        val sourceFiles = sourceCollector.collect(null, BuildType.BIN)
            .merge(sourceCollector.collect(target, BuildType.BIN)) // TODO: Scan only for main.kt and bin files
        val mainSource: Path? = sourceFiles.mainFile?.toPath()
        return listOfNotNull(
            if (mainSource?.exists() == true) {
                buildBin(releaseMode, module.name, target, resolvedDeps)
            } else {
                null
            },
        ) + sourceFiles.binFiles.map { otherBin ->
            buildBin(releaseMode, otherBin.toPath().nameWithoutExtension, target, resolvedDeps)
        }
    }

    suspend fun buildAll(releaseMode: Boolean, target: KotlinTarget): List<ArtifactResult> {
        return buildAllBins(releaseMode, target) + buildLib(releaseMode, target)
    }

    private suspend fun assembleDependencies(
        root: List<DependencyNode>,
        releaseMode: Boolean,
        target: KotlinTarget,
    ): List<DependencyNode> {
        val (newRoot, duration) = measureSeconds {
            val (mavenDependencies, mavenDuration) = measureSeconds {
                val deps = root.filter { it.dependencyConf is DependencyToml.Maven }
                    .resolveAndFlatten()
                resolver.resolveArtifacts(deps, releaseMode, target)
            }

            logger.d { "Assembled maven dependencies in ${mavenDuration}s" }

            val (localDependencies, localDuration) = measureSeconds {
                root.filter { it.dependencyConf is DependencyToml.Local }
                    .map { child -> buildChildDependency(child, releaseMode, target, downloadArtifacts = true) }
            }

            logger.d { "Assembled local dependencies in ${localDuration}s" }
            localDependencies + mavenDependencies
        }

        logger.d { "Assembled dependencies in ${duration}s" }

        return newRoot
    }

    private suspend fun buildChildDependency(
        child: DependencyNode,
        releaseMode: Boolean,
        target: KotlinTarget,
        downloadArtifacts: Boolean,
        libs: List<String>? = null,
    ): DependencyNode {
        val localManifest = checkNotNull(child.localManifest)
        val childPath = modulePath / localManifest.module.name
        val childBuilder = ModuleBuilder(localManifest, context, childPath)

        val innerDepNodes = child.children
            .filter { it.dependencyConf is DependencyToml.Local }
            .map { innerChild ->
                childBuilder.buildChildDependency(innerChild, releaseMode, target, downloadArtifacts)
            }

        val innerLibs = innerDepNodes.flatMap { it.artifacts } + libs.orEmpty()
        val result = if (downloadArtifacts) {
            when (val result = childBuilder.buildLib(releaseMode, target, innerLibs)) {
                is ArtifactResult.Success -> result.artifactPath
                ArtifactResult.NoSourceFiles -> null
                ArtifactResult.NoArtifactFound -> error("No artifact found at $childPath")
                is ArtifactResult.ProcessError -> error(result.message.orEmpty())
            }
        } else {
            null
        }

        return child.copy(
            children = innerDepNodes,
            artifacts = listOfNotNull(result),
        )
    }

    suspend fun resolveRootDependencyTree(
        targets: List<KotlinTarget>,
        scopes: List<DependencyScope> = listOf(DependencyScope.IMPLEMENTATION),
        includeCommon: Boolean = true
    ): List<DependencyNode> {
        return resolveDependencyTree(manifest, workingDirectory, targets, scopes, includeCommon)
    }

    private suspend fun resolveDependencyTree(
        rootManifest: ManifestToml,
        rootFolder: Path,
        targets: List<KotlinTarget>,
        scopes: List<DependencyScope>,
        includeCommon: Boolean
    ): List<DependencyNode> {
        return rootManifest.dependenciesFor(scopes, targets, includeCommon = includeCommon)
            .flatMap { it.value.values }
            .distinctBy { it.key }
            .map { dependency ->
                when (dependency) {
                    is DependencyToml.Local -> resolveLocalDependency(
                        dependencyConf = dependency,
                        rootFolder = rootFolder,
                        targets = targets,
                        scopes = scopes,
                        includeCommon = includeCommon
                    )

                    is DependencyToml.Maven -> resolveMavenDependency(dependency, targets)
                    is DependencyToml.Git -> TODO()
                    is DependencyToml.Npm -> TODO()
                }
            }
    }

    suspend fun fetchArtifacts(
        root: List<DependencyNode>,
        releaseMode: Boolean,
        target: KotlinTarget,
    ): List<DependencyNode> {
        // TODO: Don't build child dependencies, just download remote artifacts/sources
        return assembleDependencies(root, releaseMode, target)
    }

    private suspend fun resolveMavenDependency(
        dependencyConf: DependencyToml.Maven,
        targets: List<KotlinTarget>,
    ): DependencyNode {
        val node = DependencyNode(
            localManifest = null,
            dependencyConf = dependencyConf,
            children = emptyList(),
            artifacts = emptyList(),
        )
        // TODO: address default target selection
        return resolver.resolve(node, false, targets.first())
    }

    private suspend fun resolveLocalDependency(
        dependencyConf: DependencyToml.Local,
        rootFolder: Path,
        targets: List<KotlinTarget>,
        scopes: List<DependencyScope>,
        includeCommon: Boolean,
    ): DependencyNode {
        val packFile = rootFolder / dependencyConf.path / MANIFEST_FILENAME
        val localModule = context.loadManifestToml(packFile.toString())
        val children = resolveDependencyTree(
            localModule,
            rootFolder / dependencyConf.path,
            targets,
            scopes,
            includeCommon = includeCommon
        )
        return DependencyNode(
            localManifest = localModule,
            dependencyConf = dependencyConf,
            children = children,
            artifacts = emptyList(),
        )
    }

    @OptIn(ExperimentalStdlibApi::class)
    private suspend fun startKotlinCompiler(
        sourceFiles: List<String>,
        commonSourceFiles: List<String> = emptyList(),
        releaseMode: Boolean,
        output: Path,
        target: KotlinTarget,
        isBinary: Boolean,
        isTest: Boolean,
        libs: List<String>,
        includes: List<String> = emptyList(),
        isMultiplatform: Boolean = false,
    ): CommunicateResult {
        check(output.isAbsolute) {
            "ModuleBuilder.startKotlinCompiler(...) requires `output` to be an absolute path: $output"
        }
        val defaultJdk = checkNotNull(context.jdkInstalls.getDefaultJdk()) {
            "Run `ktpack setup` before using your project"
        }
        val outputDir = checkNotNull(output.parent).mkdirs()
        val compileOpts = outputDir / "${Random.nextBytes(6).toHexString()}.opts"
        val kotlinVersion = module.kotlinVersion ?: Ktpack.KOTLIN_VERSION
        return try {
            exec {
                workingDirectory = outputDir.toString()
                environment["JAVA_HOME"] = defaultJdk.path
                when (target) {
                    KotlinTarget.JVM -> {
                        configureJvmCompilerArgs(output, kotlinVersion, libs, compileOpts)
                    }

                    KotlinTarget.JS_NODE, KotlinTarget.JS_BROWSER -> {
                        configureJsCompilerArgs(kotlinVersion, releaseMode, output, isBinary, libs, includes, compileOpts)
                    }

                    KotlinTarget.MACOS_ARM64,
                    KotlinTarget.MACOS_X64,
                    KotlinTarget.MINGW_X64,
                    KotlinTarget.LINUX_ARM64,
                    KotlinTarget.LINUX_X64,
                    -> {
                        configureNativeCompilerArgs(
                            isBinary = isBinary,
                            outputPath = output,
                            target = target,
                            kotlinVersion = kotlinVersion,
                            releaseMode = releaseMode,
                            libs = libs,
                            compileOpts = compileOpts,
                            isTest = isTest,
                            includes = includes,
                        )
                    }
                }

                configureCommonCompilerArgs(sourceFiles, commonSourceFiles, compileOpts, isMultiplatform)
            }
        } finally {
            compileOpts.delete()
        }
    }

    private fun ExecArgumentsBuilder.configureCommonCompilerArgs(
        sourceFiles: List<String>,
        commonSourceFiles: List<String>,
        compileOpts: Path,
        isMultiplatform: Boolean,
    ) {
        if (context.debug) {
            arg("-verbose")
        }
        // arg("-nowarn")
        // arg("-Werror")

        if (isMultiplatform) {
            arg("-Xmulti-platform")
        } else {
            check(commonSourceFiles.isEmpty()) {
                "Cannot provide common source files unless compiling in multiplatform mode"
            }
        }
        //val serializationPlugin = File(context.kotlinInstalls.findKotlinHome(kotlinVersion), "lib")
        //    .nestedFile("kotlinx-serialization-compiler-plugin.jar")
        // arg("-Xplugin=${serializationPlugin.getAbsolutePath()}")

        // args("-kotlin-home", path)
        // args("-opt-in", <class>)

        if (commonSourceFiles.isNotEmpty()) {
            arg("-Xcommon-sources=${commonSourceFiles.joinToString(CPSEP)}")
        }

        (sourceFiles + commonSourceFiles).forEach { file -> arg(file) }

        // args("-language-version", "2.0")

        logger.d { "Launching Kotlin Compiler: ${arguments.joinToString(" ")}" }
        if (compileOpts.exists()) {
            logger.d { "${compileOpts.name}:\n${compileOpts.readUtf8()}" }
        }

        environment["SystemRoot"] = getEnv("windir").orEmpty()
        environment["TMP"] = TEMP_PATH.toString()
    }

    private fun ExecArgumentsBuilder.configureJvmCompilerArgs(
        outputPath: Path,
        kotlinVersion: String,
        libs: List<String>,
        compileOpts: Path,
    ) {
        val targetOutPath = "${outputPath}${KotlinTarget.JVM.executableExt}"
        arg(context.kotlinInstalls.findKotlincJvm(kotlinVersion))

        // arg("-Xjdk-release=$version")
        // args("-jvm-target", "1.8")
        arg("-include-runtime")
        // args("-jdk-home", "")

        if (libs.isNotEmpty()) {
            val opts = libs.joinToString(CPSEP, prefix = "-classpath ")
            compileOpts.writeUtf8(opts) { error ->
                throw error
            }
            arg("@${compileOpts.name}")
        }

        args("-d", targetOutPath) // output folder/ZIP/Jar path
    }

    private fun ExecArgumentsBuilder.configureJsCompilerArgs(
        kotlinVersion: String,
        releaseMode: Boolean,
        output: Path,
        isBinary: Boolean,
        libs: List<String>,
        includes: List<String>,
        compileOpts: Path,
    ) {
        val kotlincPath = context.kotlinInstalls.findKotlincJs(kotlinVersion).toPath()
        arg(kotlincPath.toString())

        if (isBinary) {
            args("-main", "call") // "noCall"
            args("-module-kind", "umd") // umd|commonjs|amd|plain
        }

        //arg("-Xir-only")
        if (releaseMode) {
            arg("-Xir-dce")
            arg("-Xoptimize-generated-js")
        }

        //arg("-Xir-build-cache")
        //compileOpts.appendUtf8("-Xcache-directory=${output.parent}", onError = { throw it })

        //arg("-Xgenerate-dts")

        if (isBinary) {
            arg("-Xir-produce-js")
        } else {
            arg("-Xir-produce-klib-file")
        }
        args("-ir-output-dir", output.parent!!.toString())
        args("-ir-output-name", output.name)
        //args("-output", targetOutPath.toString()) // output js file

        environment["JAVA_OPTS"] = "-Xmx1g"
        arg("-Xdisable-default-scripting-plugin")
        arg("-Xir-property-lazy-initialization")

        if (!isBinary) {
            arg("-meta-info")
        }
        //arg("-source-map")
        // args("-source-map-base-dirs", <path>)
        // args("-source-map-embed-sources", "never") // always|never|inlining

        val opsStringSize = includes.sumOf { it.length } + libs.sumOf { it.length }
        val compilerOptsString = StringBuilder(opsStringSize)

        if (includes.isNotEmpty()) {
            compilerOptsString.append(includes.joinToString(CPSEP, prefix = "-Xinclude="))
            compilerOptsString.append(" ")
        }

        // arg("-no-stdlib")
        // Later version of kotlinc-js fail to provide the sdk by default
        val stdlibExtension = if (Version.parse(kotlinVersion).major >= 2) "klib" else "jar"
        val jsLibs = libs + (kotlincPath.parent?.parent!! / "lib" / "kotlin-stdlib-js.$stdlibExtension").toString()
        if (jsLibs.isNotEmpty()) {
            val archiveLibFiles = jsLibs.filter {
                it.endsWith(".klib") || it.endsWith(".jar")
            }

            val optString = archiveLibFiles.joinToString(CPSEP, prefix = "-libraries ")
            compilerOptsString.append(optString)
        }
        compileOpts.appendUtf8(compilerOptsString.toString(), onError = { throw it })
        arg("@${compileOpts.name}")
    }

    private fun ExecArgumentsBuilder.configureNativeCompilerArgs(
        isBinary: Boolean,
        outputPath: Path,
        target: KotlinTarget,
        kotlinVersion: String,
        releaseMode: Boolean,
        libs: List<String>,
        compileOpts: Path,
        includes: List<String>,
        isTest: Boolean,
    ) {
        val targetOutPath = if (isBinary) {
            "$outputPath${target.executableExt}".toPath()
        } else {
            outputPath // library suffix will be added be the compiler
        }
        targetOutPath.parent?.mkdirs()

        arg(context.kotlinInstalls.findKotlincNative(kotlinVersion))
        args("-target", target.name.lowercase())
        args("-output", targetOutPath.toString()) // output kexe or exe file

        if (isTest) {
            arg("-generate-test-runner")
            // args("-generate-worker-test-runner", "")
            // args("-generate-no-exit-test-runner", "")
        } else {
            // args("-entry", "") // TODO: Handle non-root package main funcs
        }

        if (isBinary || isTest) {
            args("-produce", "program")
        } else {
            args("-produce", "library") // static, dynamic, framework, library, bitcode
        }

        if (releaseMode) {
            arg("-opt") // kotlinc-native only: enable compilation optimizations
        } else {
            arg("-g") // kotlinc-native only: emit debug info
            arg("-enable-assertions")
        }

        if (libs.isNotEmpty()) {
            val libFlag = "-library "
            val libList = libs.joinToString("\n") { libFlag + it }
            compileOpts.writeUtf8(libList) { throw it }
            args("@${compileOpts.name}")
        }

        if (includes.isNotEmpty()) {
            args(includes.joinToString(";", prefix = "-Xinclude="))
        }

        // args("-manifest", "")
        // args("-module-name", "")
        // args("-nomain", "")
        // args("-nopack", "")
        // args("-no-default-libs", "") // TODO: Disable for COMMON_ONLY modules
        // args("-nostd", "")

        // args("-repo", "")
        // args("-linker-option", "")
        // args("-linker-options", "")
        // args("-native-library", "")
        // args("-include-binary", "")
    }
}
