name: Publish Release

on:
  push:
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'docs/requirements.txt'

      - name: Install Python dependencies
        run: python3 -m pip install -r ./docs/requirements.txt

#      - uses: gradle/actions/setup-gradle@v4
#      - name: Build KDocs
#        run: ./gradlew clean dokkaHtmlMultiModule

#      - name: Move KDoc build
#        run: mv build/dokka/htmlMultiModule docs/kdoc

      - name: Deploy with mike
        run: |
          VERSION=${GITHUB_REF_NAME#v} mike deploy --update-aliases --push ${{ github.ref_name }} latest

  publish-cli-windows:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-clang
      - name: Disable Visual Studio
        run: move "C:\Program Files\Microsoft Visual Studio" "C:\Program Files\Microsoft Visual Studio2"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.konan
            %USERPROFILE%\.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - name: Build CLI
        run: ./gradlew packageReleaseWindows

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: true
          files: |
            ktpack-cli/build/release/ktpack-windows.zip
            ktpack-cli/build/release/ktpack-windows.zip.sha256

  publish-cli-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Install libcurl
        run:  |
          sudo apt update
          sudo apt install libcurl4-openssl-dev

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - name: Build CLI
        run: ./gradlew packageReleaseLinux

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: true
          files: |
            ktpack-cli/build/release/ktpack-linux.zip
            ktpack-cli/build/release/ktpack-linux.zip.sha256

  publish-cli-macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - name: Build CLI
        run: ./gradlew packageReleaseMacos --no-parallel

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: true
          files: |
            ktpack-cli/build/release/ktpack-macos.zip
            ktpack-cli/build/release/ktpack-macos.zip.sha256
