name: Publish Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.check.outputs.any_changed }}
      docs: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: check
        uses: tj-actions/changed-files@v28
        with:
          files: |
            .github/workflows/publish.yml
            **/build.gradle.kts
            gradle/libs.versions.toml
            gradle/kotlin-js-store/**
            ktpack/src/**/*.kt
      - name: Get changed files
        id: docs
        uses: tj-actions/changed-files@v28
        with:
          files: |
            docs/**/*.md
            mkdocs.yml

  publish-docs:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.docs == 'true' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get version
        uses: DrewCarlson/action-get-tag@v4
        with:
          strip_v: true
          env_var_name: KTPACK_VERSION
      - uses: actions/checkout@v3
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          REQUIREMENTS: docs/requirements.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml

  publish-ktpack-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Build CLI
        with:
          arguments: :ktpack-script:shadowJar

      - name: Compress and checksum
        run: |
          mv ktpack-script/build/libs/ktpack-script.jar ktpack-script.jar
          shasum -a 256 ktpack-script.jar > ktpack-script.jar.sha256

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          files: |
            ktpack-script.jar
            ktpack-script.jar.sha256

  publish-cli-windows:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-clang
      - name: Disable Visual Studio
        run: move "C:\Program Files\Microsoft Visual Studio" "C:\Program Files\Microsoft Visual Studio2"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            %USERPROFILE%\.konan
            %USERPROFILE%\.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Build CLI
        with:
          arguments: packageReleaseWindowsX64

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          files: |
            ktpack/build/release/ktpack-windows.zip
            ktpack/build/release/ktpack-windows.zip.sha256

  publish-cli-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Install libcurl
        run:  |
          sudo apt update
          sudo apt install libcurl4-openssl-dev

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Build CLI
        with:
          arguments: packageReleaseLinuxX64

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          files: |
            ktpack/build/release/ktpack-linux.zip
            ktpack/build/release/ktpack-linux.zip.sha256

  publish-cli-macos:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    needs: [ file-changes ]
    if: needs.file-changes.outputs.any == 'true' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Build CLI
        with:
          arguments: packageReleaseMacos --no-parallel

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          files: |
            ktpack/build/release/ktpack-macos.zip
            ktpack/build/release/ktpack-macos.zip.sha256
