name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] #windows-latest
        compiler: [clang]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Build files
        uses: actions/cache@v2
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - name: Add clang path to $PATH env (Windows)
        shell: bash
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: echo "PATH=C:\mingw64\bin:$PATH" >> $GITHUB_ENV
      - name: Remove Visual Studio installs (Windows)
        shell: bash
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: mkdir "/c/Program Files (x86)/vs/" && mv /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio* "/c/Program Files (x86)/vs/"
      - uses: eskatos/gradle-command-action@v1
        name: Test Windows Target
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          arguments: windowsX64Test
      - uses: eskatos/gradle-command-action@v1
        name: Test Apple Targets
        if: ${{ startsWith(matrix.os, 'macos') }}
        with:
          arguments: macosX64Test
      - uses: eskatos/gradle-command-action@v1
        name: Test Linux Target
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          arguments: linuxX64Test
